---
name: Docs

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7

      - name: Set up mise
        uses: jdx/mise-action@f10502fc09dadecfefb962fff68ce77213930204  # v4.2.2

      - name: Build docs
        run: mise run docs:build

  lint-markdown:
    name: Lint markdown
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7

      - name: Set up mise
        uses: jdx/mise-action@f10502fc09dadecfefb962fff68ce77213930204  # v4.2.2

      - name: Lint docs markdown
        run: mise run docs:lint
